name: swe-agent
dependencies:
  - python=3.9
  - pip
  - pip:
    - anthropic
    - config
    - datasets
    - docker
    - gymnasium
    - numpy
    - openai>=1.0
    - pandas
    - rich
    - ruamel.yaml
    - swebench>=1.0.1
    - tenacity
    - unidiff
    - simple-parsing
    - together
    - ollama
    - rich-argparse
