site_name: SWE-agent documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/swe-agent.svg
  palette: 

    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night

        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes 
    - content.action.edit
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
nav:
  - Home: index.md
  - Installation:
    - "installation/index.md"
    - "Use in-browser": "installation/codespaces.md"
    - "Install from source": "installation/source.md"
    - "Docker": "installation/docker.md"
    - "Adding your keys": "installation/keys.md"
    - "Installation tips": "installation/tips.md"
    - "Changelog": "installation/changelog.md"
  - Usage:
    - "usage/index.md"
    - "Command line usage": "usage/cl_tutorial.md"
    - "Using the web UI": "usage/web_ui.md"
    - "Trajectories": "usage/trajectories.md"
    - "Trajectory inspector": "usage/inspector.md"
    - "FAQ": "usage/faq.md"
    - "Benchmarking": "usage/benchmarking.md"
  - Development:
    - "Modifying swe-agent": "dev/modify.md"
    - "Config files": "dev/config.md"
    - "Command definitions": "dev/commands.md"
    - "Demonstrations": "dev/demonstrations.md"
    - "Contribution guide": "dev/contribute.md"

plugins:
   - glightbox

repo_url: https://github.com/princeton-nlp/SWE-agent
repo_name: princeton-nlp/SWE-agent
edit_uri: edit/main/docs/