site_name: SWE-agent documentation
theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
    annotation: material/chevron-right-circle
  logo: assets/swe-agent.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: deep orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - content.action.edit
    - navigation.footer
    - content.code.copy
    - content.footnote.tooltips
    - header.autohide
    - announce.dismiss
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.magiclink
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
nav:
  - Home: index.md
  - Project Overview:
    - "background/index.md"
    - "Agent-Computer Interface": "background/aci.md"
    - "Interactive Agent Tools": "background/iat.md"
    - "Architecture": "background/architecture.md"
  - Installation:
    - "installation/index.md"
    - "Use in-browser": "installation/codespaces.md"
    - "Install from source": "installation/source.md"
    - "Run with docker": "installation/docker.md"
    - "API keys": "installation/keys.md"
    - "Installation tips": "installation/tips.md"
    - "Changelog": "installation/changelog.md"
  - Usage:
    - "usage/index.md"
    - "Command line usage": "usage/cl_tutorial.md"
    - "EnIGMA usage": "usage/enigma.md"
    - "Solving coding challenges": "usage/coding_challenges.md"
    - "Using the web UI": "usage/web_ui.md"
    - "Trajectories": "usage/trajectories.md"
    - "Trajectory inspector": "usage/inspector.md"
    - "FAQ": "usage/usage_faq.md"
    - "Benchmarking": "usage/benchmarking.md"
  - Configuration:
    - "Config files": "config/config.md"
    - "Command definitions": "config/commands.md"
    - "Demonstrations": "config/demonstrations.md"
    - "Environment variables": "config/env.md"
    - "Docker images": "config/docker.md"
    - "Summarizers": "config/summarizers.md"
  - Development:
    - "Contribution guide": "dev/contribute.md"
    - "Formatting conflicts": "dev/formatting_conflicts.md"
  - Reference:
    - "reference/index.md"
    - "Problem statements": "reference/problem_statements.md"
    - "Repository": "reference/repo.md"
    - "Model config": "reference/model_config.md"
    - "Agent config": "reference/agent_config.md"
    - "Environment config": "reference/env_config.md"
    - "Agent class": "reference/agent.md"
    - "Environment class": "reference/env.md"
  - "FAQ": "faq.md"
plugins:
   - glightbox
   - search
   - include-markdown
   - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [sweagent]
          options:
            merge_init_into_class: true
            summary: false
            show_root_heading: true
            heading_level: 2
            docstring_style: google
            show_if_no_docstring: true
            show_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
              - griffe_pydantic:
                  schema: false
            filters:
              - "!^_"
              - "!^model_config"
              - "!^model_post_init"
repo_url: https://github.com/princeton-nlp/SWE-agent
repo_name: princeton-nlp/SWE-agent
edit_uri: edit/main/docs/
extra_css:
  - assets/custom.css
  - assets/mkdocstrings.css