blank_issues_enabled: true
contact_links:
  - name: Discord server
    url: https://discord.gg/AVEFbBn2rH
    about: Developers and users can be found on the Discord server
  - name: Blank issue
    url: https://github.com/princeton-nlp/SWE-agent/issues/new
    about: None of the above? Open a blank issue